#!/bin/sh

set -ue

DEBUG="${DEBUG:-}"

: "${SLPT_API_KEY_COMMAND:="echo mysecretpassword"}" # example: pass show api/openai.com/chatgpt/john-doe

usage() {
  printf 'usage: slpt PROMPT\n' #"$(basename "${0}")"
  printf 'flags:\n'
  # printf '  -s | --system    \n'
  printf '  -c, --chat NAME          specify chat [default: last used] (created if does not exist)\n'
  printf '  -m, --model NAME         specify model [default: "gpt-3.5-turbo"]\n'
  # shellcheck disable=2016
  printf '  -o, --chat-folder PATH   specify folder for chat\n'
  printf '  -t, --temperature N      specify temperature [default: 1.0]\n'
  printf '  -p, --top-probability N  specify top probability [default: 1.0]\n'
  printf '  -s, --system PROMPT      specify system prompt\n'
}

get_content() {
  response="$(jq -r '.choices[0].message.content')"
  printf '%s\n' "${response#"${response%%[![:space:]]*}"}"
}

api_call() {
  content="$(printf '%s' "${1}" | jq -R -s . | sed 's/^"//;s/"$//')"
  model="${2:-"gpt-3.5-turbo"}"
  temperature="${3:-"1.0"}"
  top_probability="${4:-"1.0"}"
  system=""
  data="$(
    printf '
    {
      "messages": [
        {
          "role": "user",
          "content": "%s"
        },
        {
          "role": "system",
          "content": "%s"
        }
      ],
      "model": "%s",
      "temperature": %s,
      "top_p": %s
    }' \
      "${content}" \
      "${system}" \
      "${model}" \
      "${temperature}" \
      "${top_probability}"
  )"
  # shellcheck disable=2016
  curl \
    --silent \
    --request POST \
    --header 'Content-Type: application/json' \
    --header "Authorization: Bearer $(sh -c "${SLPT_API_KEY_COMMAND}")" \
    --data "${data}" \
    'https://api.openai.com/v1/chat/completions'
}

[ "${#}" -lt 1 ] && usage && exit 1

response="$(api_call "${*}")"

[ -n "${DEBUG}" ] && printf '%s' "${response}" >&2

printf '%s' "${response}" | get_content
